version: "3.8"

x-mm-env: &mm-env
  - CHAIN_ID=localosmosis
  - MANTLEMINT_HOME=/app
  - INDEXER_DB=/data/indexer
  - MANTLEMINT_DB=/data/mantlemint
  - GENESIS_PATH=/app/config/genesis.json
  - DISABLE_SYNC=false
  - RUST_BACKTRACE=full
  - ENABLE_EXPORT_MODULE=false
  - RICHLIST_LENGTH=100
  - RICHLIST_THRESHOLD=1uluna
  - ACCOUNT_ADDRESS_PREFIX=osmo
  - BOND_DENOM=uluna
  - LCD_ENDPOINTS=http://osmosisd:1317
  - RPC_ENDPOINTS=http://osmosisd:26657
  - WS_ENDPOINTS=ws://osmosisd:26657/websocket

services:
  osmosisd:
    image: ghcr.io/osmosis-labs/localosmosis:${OSMOSIS_VERSION:-latest}
    hostname: osmosisd
    volumes:
      - osmosis:/app
    networks:
      - default
    ports:
      - "8080:8080"
      - "26657:26657"

  mantlemint:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/osmosis-labs/mantlemint:${OSMOSIS_VERSION:-latest}
    hostname: mantlemint
    command: /usr/local/bin/mantlemint
    environment: *mm-env
    restart: unless-stopped
    volumes:
      - osmosis:/app
    networks:
      - default
    ports:
      - 1317:1317
      - 9090:9090

volumes:
  osmosis:

networks:
  default:
